apiVersion: v1
kind: Pod
metadata:
  name: aegis-insecure-latest
  namespace: aegis-policy-test

spec:
  restartPolicy: Never

  containers:
    - name: latest-container
      image: nginx:latest

      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
