apiVersion: v1
kind: Pod
metadata:
  name: aegis-insecure-security-context
  namespace: aegis-policy-test

spec:
  restartPolicy: Never

  containers:
    - name: insecure-container
      image: mcr.microsoft.com/oss/v2/kubernetes/pause@sha256:1a5786ee0e19956a36d3bc8ae3dce4e7203e1a07e4e6495d6b4c5d465203ec5a

      securityContext:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: true
