apiVersion: v1
kind: Pod
metadata:
  name: aegis-insecure-no-digest
  namespace: aegis-policy-test

spec:
  restartPolicy: Never

  containers:
    - name: tagged-container
      image: nginx:1.27

      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
